#!/bin/bash
install() {
	if [[ -e bundle/$1-$2 ]] ; then
		cd bundle/$1-$2
		echo "Updating $1-$2"
		git pull
		cd ../..
	else
		echo "Installing $1-$2"
		git clone http://github.com/$1/$2.git bundle/$1-$2
	fi
}

install tpope vim-fugitive
install xolox vim-lua-ftplugin
install evanmiller nginx-vim-syntax
